apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datacalc # must match the claimRef defined on PersistenVolume
  namespace: default
  labels:
    app: engine
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 50Gi
